# Generated by Django 5.2.5 on 2025-08-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
